spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}
app.security.jwt.secret=${JWT_SECRET}
app.security.master-key=${MASTER_KEY}
app.security.api-key-pepper=${API_KEY_PEPPER}
app.bootstrap.enabled=false
app.sunat.xsd.enabled=true
spring.jpa.properties.hibernate.generate_statistics=false
server.forward-headers-strategy=framework

app.sunat.xsd.path=${SUNAT_XSD_PATH:/opt/perubilling/sunat-xsd}
app.public.base-url=${PUBLIC_BASE_URL}
management.endpoint.health.show-details=never
app.sunat.xsd.fail-fast=true

springdoc.api-docs.enabled=false
springdoc.swagger-ui.enabled=false

app.artifacts.require-checksum=true
app.summary.auto-enabled=true

app.artifacts.backend=${ARTIFACTS_BACKEND:database}
app.production.guard.enabled=${PRODUCTION_GUARD_ENABLED:true}


management.endpoint.health.group.liveness.show-details=never
management.endpoint.health.group.readiness.show-details=never
