app.security.jwt.secret=bG9jYWwtZGV2LWp3dC1zZWNyZXQtMzItYnl0ZXMtbWluaW11bQ==
app.security.master-key=cGVydWJpbGxpbmctbG9jYWwtbWFzdGVyLWtleS0zMiE=
app.security.api-key-pepper=local-api-key-pepper-development-only-32plus

app.bootstrap.enabled=${BOOTSTRAP_ENABLED:true}
app.bootstrap.admin-email=${BOOTSTRAP_ADMIN_EMAIL:admin@local.test}
app.bootstrap.admin-password=${BOOTSTRAP_ADMIN_PASSWORD:ChangeMe123!}
app.sunat.xsd.enabled=${SUNAT_XSD_ENABLED:false}
